### ISSUE TITLE
toMode incorrect

### ISSUE THREAD

**Issue by yckart** [bahamas10/node-perms#1]
``` javascript
toMode("rwxr-xr-x") // => 493
```

**Comment by bahamas10** [comment]
Actually, that is correct :)

The modes that we are used to seeing (for example, "755") is actually an octal representation of a number.  So 493 represented in octal is 755.

``` js
> 493 === 0755
true
```

You can call `toString(8)` on the number to get it as a string in base 8 which is probably what you would expect

``` js
> (493).toString(8)
'755'
```
